### ISSUE TITLE
SocialView.OnSocialClickListener() doesn't exist anymore?

### ISSUE THREAD

**Issue by mihudevcom** [hendraanggrian/socialview#27]
In the description you mentioned SocialView.OnSocialClickListener() to know when you click a mention or a hashtag. But it seems it doesn't exist anymore? I need something like this so I know what the user selected from the list. Any solutions?

**Comment by hendraanggrian** [comment]
Sorry for late reply, I was preoccupied with other projects. Since I based this lib with Kotlin, `OnSocialClickListener` is replaced with Kotlin's function types. On Java, it would look like `Function<SocialView, String>() { ... }`. I will update README.md in coming days to clear up such confusion, thanks for pointing that out and let me know if I can be more of help!
