### ISSUE TITLE
Social Suggestion Box UI Shadow

### ISSUE THREAD

**Issue by abhyag** [hendraanggrian/socialview#39]
hi.. Can you please help with the UI of social mention suggestion Box . I need to remove the shadow and elevation in the suggestion box. Can it be done ? Pls help

**Comment by hendraanggrian** [comment]
Hi there, the suggestion box you are referring to is a `MultiAutoCompleteTextView` from `appcompat-v7`. At this time I wanna make sure that every layout component is default to ensure small library size.

But since all classes in this library is open, you can make a custom view yourself. See `socialview-commons` for example. I'm sorry I can't be more of help.
