### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by magnoleal** [HendraAnggrian/socialview#5]
The library is hosted in jcenter?

I'm include jcenter in repositories in the gradle, but the library is Failed to resolve.

**Comment by HendraAnggrian** [comment]
@magnoleal my bad, I failed to mention that there was an issue with jCenter since I changed the group ID. Until the issue is resolved (which I am still waiting response from jfrog's support), I'm afraid you'd have to include my maven url 'https://dl.bintray.com/hendraanggrian/maven'.

Something like this on your top build.gradle:
```gradle
allprojects {
    repositories {
        jcenter()
        maven { url 'https://dl.bintray.com/hendraanggrian/maven' }
    }
}
```

**Comment by magnoleal** [comment]
@HendraAnggrian Ow, now works fine, thanks and good job!

**Comment by HendraAnggrian** [comment]
Thank you and let me know any issue you found with the library, because the testing part is I guess what is lacking from my effort here.

**Comment by magnoleal** [comment]
Ok
