### ISSUE TITLE
custom RecyclerVIew

### ISSUE THREAD

**Issue by ErfanDP** [hendraanggrian/socialview#95]

**Comment by ErfanDP** [comment]
hey I Want to move the suggested mention box to else where and i can't find good way to do soo 
Is there a way at all?

**Comment by hendraanggrian** [comment]
Yes you can use your own layout, you just need to create your own adapter extending `SocialAdapter` (see README example or read `socialview-commons` source).

Using `RecyclerView` on the other hand, is not supported by `MultiAutoCompleteTextView`, which is a parent class of `AutoCompleteTextView`. They only support `ListAdapter`.

If you're still having issues, share your code and I will help as much as I can. In the meantime, this issue is closed.
